import ds from './Content.module.scss'
import { Title } from './Title'

const Content = () => {
  return (
    <div className={ds.centerer}>
      <div className={ds.content}>
        <Title />
        <div>
          <p style={{ fontSize: 100 }}>PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE</p>
          <p>PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE</p>
          <p>PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE</p>
          <p>PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE</p>
          <p>PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE</p>
          <p>PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE</p>
          <p>PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE</p>
          <p>PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE</p>
          <p>PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE</p>
          <p>PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE</p>
          <p>PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE</p>
          <p>PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE</p>
          <p>PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE</p>
          <p>PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE</p>
          <p>PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE</p>
          <p>PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE</p>
          <p>PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE</p>
          <p>PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE</p>
          <p>PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE</p>
          <p>PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE</p>
          <p>PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE</p>
          <p>PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE</p>
          <p>PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE</p>
          <p>PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE</p>
          <p>PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE</p>
          <p>PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE</p>
          <p>PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE</p>
          <p>PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE</p>
          <p>PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE</p>
          <p>PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE</p>
          <p>PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE</p>
          <p>PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE</p>
          <p>PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE</p>
          <p>PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE</p>
          <p>PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE</p>
          <p>PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE</p>
          <p>PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE</p>
          <p>PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE</p>
          <p>PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE</p>
          <p>PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE</p>
          <p>PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE</p>
          <p>PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE</p>
          <p>PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE</p>
          <p>PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE</p>
          <p>PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE</p>
          <p>PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE</p>
          <p>PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE</p>
          <p>PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE</p>
          <p>PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE</p>
          <p>PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE</p>
          <p>PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE</p>
          <p>PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE</p>
          <p>PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE</p>
          <p>PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE</p>
          <p>PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE</p>
          <p>PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE</p>
          <p>PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE</p>
          <p>PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE</p>
          <p>PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE</p>
          <p>PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE</p>
          <p>PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE</p>
          <p>PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE</p>
          <p>PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE</p>
          <p>PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE</p>
          <p>PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE</p>
          <p>PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE</p>
          <p>PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE</p>
          <p>PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE</p>
          <p>PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE</p>
          <p>PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE</p>
          <p>PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE</p>
          <p>PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE PAGE</p>
        </div>
      </div>
    </div>
  )
}

export { Content }
